replicas: 1
namespace: argocd
ingress:
  enabled: true
  hostname: argocd.topkek.cloud
  annotations:
    kubernetes.io/ingress.class: "traefik"
  tls:
    enabled: true
    secretName: argocd-topkek-cloud-tls
argocd:
  adminPassword: changeme

