elasticsearch:
  replicas: 1
  esJavaOpts: "-Xmx1g -Xms1g"
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        cpu: "1000m"
        memory: "4Gi"
        storage: 30Gi
  labels:
    app: elasticsearch-master
  networkPolicy:
    http:
      enabled: true
    transport:
      enabled: true
  protocol: http
  httpPort: 9200
  transportPort: 9300

logstash:
  enabled: true
  replicas: 1
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi
  logstashConfig:
    logstash.yml: |
      http.host: "0.0.0.0"
      xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]
  secretMounts:
    - name: "elasticsearch-master-certs"
      secretName: "elasticsearch-master-certs"
      path: "/usr/share/logstash/config/elasticsearch-master-certs"
  extraEnvs: 
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: password
  logstashPipeline:
    logstash.conf: |
      input {
        tcp {
          port => 5044
          codec => json
        }
      }
      output {
        elasticsearch {
          hosts => ["http://elasticsearch-master.monitoring.svc.cluster.local:9200"]
          cacert => /usr/share/logstash/config/elasticsearch-master-certs/ca.crt
          user => '${ELASTICSEARCH_USERNAME}'
          passwrod => '${ELASTICSEARCH_PASSWORD}'
          index => "logstash-%{+YYYY.MM.dd}"
        }
      }
  labels:
    app.kubernetes.io/name: logstash
    elasticsearch-master-http-client: "true"
