elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  esJavaOpts: "-Xmx1g -Xms1g"
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi
  labels:
    app.kubernetes.io/name: elasticsearch
logstash:
  enabled: true
  replicas: 1
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi
  logstashConfig:
    logstash.yml: |
      http.host: "0.0.0.0"
      xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]
  logstashPipeline:
    logstash.conf: |
      input {
        tcp {
          port => 5044
          codec => json
        }
      }
      output {
        elasticsearch {
          hosts => ["http://elasticsearch-master:9200"]
          index => "logstash-%{+YYYY.MM.dd}"
        }
      }
  labels:
    app.kubernetes.io/name: logstash

