elasticsearch:
  replicas: 3
  minimumMasterNodes: 2
  esJavaOpts: "-Xmx1g -Xms1g"
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 30Gi
  labels:
    app: elasticsearch-master
  networkPolicy:
    http:
      enabled: true
    transport:
      enabled: true
  protocol: http
  httpPort: 9200
  transportPort: 9300

logstash:
  enabled: true
  replicas: 1
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi
  logstashConfig:
    logstash.yml: |
      http.host: "0.0.0.0"
      xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]
  logstashPipeline:
    logstash.conf: |
      input {
        tcp {
          port => 5044
          codec => json
        }
      }
      output {
        elasticsearch {
          hosts => ["http://elasticsearch-master.monitoring.svc.cluster.local:9200"]
          index => "logstash-%{+YYYY.MM.dd}"
        }
      }
  labels:
    app.kubernetes.io/name: logstash
    elasticsearch-master-http-client: "true"
