apiVersion: v2
name: mastodon
description: A Helm chart for setting up mastodon instance
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mastodon
    version: 1.0.5
    repository: "https://charts.codechem.com/codechem/mastodon"

