apiVersion: v2
name: gitea
description: A Helm chart for setting up Gitea
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: gitea
    version: 10.2.0
    repository: "https://dl.gitea.io/charts"

