---
- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
    dest: /usr/local/bin/docker-compose
    mode: '0755'
