{{- if not (lookup "v1" "Secret" .Values.namespace "argocd-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  admin.password: {{ .Values.argocd.adminPassword | b64enc }}
{{- end }}

