apiVersion: v2
name: ollama
description: A Helm chart for setting up Ollama
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: ollama
    version: 0.40.0
    repository: "https://otwld.github.io/ollama-helm/"

