apiVersion: v2
name: ollama
description: A Helm chart for setting up Ollama
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: open-webui
    version: "3.0.5"
    repository: "https://helm.openwebui.com/"

