ollama:
  replicaCount: 1

  ollama:
    gpu:
      enabled: true

      type: 'nvidia'
      number: 1

    models: [llama3]


  persistentVolume:
    enabled: true


  nodeSelector:
    arch: "amd64"
    gpu: "nvidia"

