apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: log-storage
spec:
  version: "8.14.1"
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
