apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: log-storage
spec:
  version: 8.14.1
  count: 1
  elasticsearchRef:
    name: log-storage
    namespace: default

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "default"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - logs.topkek.cloud
    secretName: kibana-tls
  rules:
  - host: logs.topkek.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-storage-kb-http
            port:
              number: 5601

