apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: log-storage
spec:
  version: 8.14.1
  count: 1
  elasticsearchRefs:
  - name: log-storage
    clusterName: default
  config: 
    pipeline.workers: 4
    log.level: debug
