apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: log-storage
spec:
  count: 1
  elasticsearchRefs:
    - name: log-storage
      clusterName: default
  version: 8.14.1
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        filter {
          json {
            source => "[_source]"
          }
        }
        output {
          elasticsearch {
            hosts => [ "${DEFAULT_ES_HOSTS}" ]
            user => "${DEFAULT_ES_USER}"
            password => "${DEFAULT_ES_PASSWORD}"
            ssl_certificate_authorities => "${DEFAULT_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044
