loki:
  deploymentMode: SingleBinary
  loki:
    auth_enabled: false
    analytics:
      reporting_enabled: false
    commonConfig:
      replication_factor: 1
    ingester:
      chunk_encoding: snappy
    storage:
      type: filesystem
    schemaConfig:
      configs:
        - from: "2024-06-29"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    limits_config:
      retention_period: 14d
    mminio:
      enabled: true
      serviceAccount:
        name: "minio-sa-loki"

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 50Gi
      gateway:
        replicas: 0
      backend:
        replicas: 0
      read:
        replicas: 0
      write:
        replicas: 0
      chunksCache:
        enabled: false
      resultsCache:
        enabled: false
      lokiCanary:
        enabled: false
      test:
        enabled: false
promtail:
  fullnameOverride: promtail
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /run/promtail/positions.yaml
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
            - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  persistence:
    enabled: true
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    size: 5Gi

