deploymentMode: SingleBinary

loki:
  fullnameOverride: loki
  persistence:
    enabled: true
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    auth_enabled: false
    pattern_ingester:
      enabled: false
    tracing:
      enabled: false
    storage:
      type: filesystem
      bucketNames:
        chunks: "loki-chunks"
    schemaConfig:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    commonConfig:
      replication_factor: 1
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
    distributor:
      ring:
        kvstore:
          store: inmemory
    ruler:
      storage:
        type: local
      rule_path: /loki/rules-temp

promtail:
  fullnameOverride: promtail
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /run/promtail/positions.yaml
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  persistence:
    enabled: true
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    size: 5Gi

