#!/bin/bash

set -e

function createSecret() {
  local secretName=$1
  local secretKey=$2
  local secretValue=$3

  kubectl create secret generic $secretName --from-literal=$secretKey=$secretValue
}

function help() {
  echo "Usage: create-secret <secret name> <secret key> <secret value>"
}

case "$#" in
  3)
    createSecret $1 $2 $3
    ;;
  *)
    help
    ;;
esac
