apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-applicationset
  namespace: default
spec:
  generators:
  - list:
      elements:
      - chart: grafana
        path: tools/grafana
      - chart: prometheus
        path: tools/prometheus
      - chart: eck-operator
        path: tools/eck-operator
  template:
    metadata:
      name: '{{chart}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/makefunstuff/k3s-lab'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

