apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master
  labels:
    app: elasticsearch
    role: master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  labels:
    app: elasticsearch
    role: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard

