---
- name: Install Caddy
  shell: |
    apt install -y debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | apt-key add -
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
    apt update
    apt install caddy

- name: Setup Caddy for SourceHut and Soft-Serve
  copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
  notify: Reload Caddy

