global:
  namespace: monitoring

grafana:
  deployment:
    labels:
      elasticsearch-master-http-client: "true"
      app.kubernetes.io/name: grafana
  service:
    labels:
      elasticsearch-master-http-client: "true"
      app.kubernetes.io/name: grafana
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "default"
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.topkek.cloud
    path: /
    tls:
      - hosts:
          - grafana.topkek.cloud
        secretName: grafana-tls
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.monitoring.svc.cluster.local
          isDefault: true
        - name: Elasticsearch
          type: elasticsearch
          access: proxy
          url: http://elasticsearch-master.monitoring.svc.cluster.local:9200
          jsonData:
            esVersion: 7
            timeField: "@timestamp"
