global:
  namespace: monitoring

grafana:
  deployment:
    labels:
      app.kubernetes.io/name: grafana
  service:
    labels:
      app.kubernetes.io/name: grafana
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "default"
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.topkek.cloud
    path: /
    tls:
      - hosts:
          - grafana.topkek.cloud
        secretName: grafana-tls
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.monitoring.svc.cluster.local
          isDefault: true
